// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Account
{
    public string Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Role { get; set; }

    public string WalletId { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Counselor> Counselors { get; set; } = new List<Counselor>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual Wallet Wallet { get; set; }
}