// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Answer
{
    public string Id { get; set; }

    public string QuestionId { get; set; }

    public string Text { get; set; }

    public bool? IsCorrect { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? Score { get; set; }

    public string Tag { get; set; }

    public int? Status { get; set; }

    public virtual Question Question { get; set; }
}