// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Booking
{
    public string Id { get; set; }

    public string MemberId { get; set; }

    public string Member2Id { get; set; }

    public string CounselorId { get; set; }

    public string Note { get; set; }

    public DateTime? TimeStart { get; set; }

    public DateTime? TimeEnd { get; set; }

    public double? Price { get; set; }

    public string CancelReason { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Rating { get; set; }

    public string Feedback { get; set; }

    public bool? IsCouple { get; set; }

    public string ProblemSummary { get; set; }

    public string ProblemAnalysis { get; set; }

    public string Guides { get; set; }

    public bool? IsReport { get; set; }

    public string ReportMessage { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<BookingSubCategory> BookingSubCategories { get; set; } = new List<BookingSubCategory>();

    public virtual Counselor Counselor { get; set; }

    public virtual Member Member { get; set; }

    public virtual Member Member2 { get; set; }
}