// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Category
{
    public string Id { get; set; }

    public string Name { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<PersonType> PersonTypes { get; set; } = new List<PersonType>();

    public virtual ICollection<ResultPersonType> ResultPersonTypes { get; set; } = new List<ResultPersonType>();

    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}