// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Chapter
{
    public string Id { get; set; }

    public int? ChapNum { get; set; }

    public string CourseId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ChapterType { get; set; }

    public string ChapNo { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Processing> Processings { get; set; } = new List<Processing>();
}