// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class CounselorSubCategory
{
    public string Id { get; set; }

    public string SubCategoryId { get; set; }

    public string CounselorId { get; set; }

    public string CategoryId { get; set; }

    public string CertifivationId { get; set; }

    public string Name { get; set; }

    public int? Status { get; set; }

    public virtual Counselor Counselor { get; set; }

    public virtual SubCategory SubCategory { get; set; }
}