// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Counselor
{
    public string Id { get; set; }

    public string AccountId { get; set; }

    public string Avatar { get; set; }

    public string Fullname { get; set; }
    public string Description { get; set; }
    public double Price { get; set; }
    public double Rating { get; set; }
    public int Reviews { get; set; }
    public int YearOfJob { get; set; }
    public string Phone { get; set; }
    public int? Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Certification> Certifications { get; set; } = new List<Certification>();

    public virtual ICollection<CounselorSubCategory> CounselorSubCategories { get; set; } = new List<CounselorSubCategory>();

    public virtual ICollection<WorkSchedule> WorkSchedules { get; set; } = new List<WorkSchedule>();
}