// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Couple
{
    public string Id { get; set; }

    public string Member { get; set; }

    public string Member1 { get; set; }

    public string Mbti { get; set; }

    public string Disc { get; set; }

    public string LoveLanguage { get; set; }

    public string BigFive { get; set; }

    public string Mbti1 { get; set; }

    public string Disc1 { get; set; }

    public string LoveLanguage1 { get; set; }

    public string BigFive1 { get; set; }

    public string MbtiDescription { get; set; }
    public string DiscDescription { get; set; }
    public string LoveLanguageDescription { get; set; }
    public string BigFiveDescription { get; set; }

    public string Mbti1Description { get; set; }
    public string Disc1Description { get; set; }
    public string LoveLanguage1Description { get; set; }
    public string BigFive1Description { get; set; }

    public string MbtiResult { get; set; }

    public string DiscResult { get; set; }

    public string LoveLanguageResult { get; set; }

    public string BigFiveResult { get; set; }

    public bool? IsVirtual { get; set; }

    public string VirtualName { get; set; }

    public DateTime? VirtualDob { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Rec1 { get; set; }

    public string Rec2 { get; set; }

    public int? CreateGender { get; set; }

    public int? Status { get; set; }

    public string? AccessCode { get; set; }

    public string? VirtualAvatar { get; set; }
    public string? VirtualDescription { get; set; }
    public string? VirtualRelationship { get; set; }
    public string? VirtualGender { get; set; }

    public virtual Member Member1Navigation { get; set; }

    public virtual Member MemberNavigation { get; set; }
}