// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Course
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Thumble { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public double? Price { get; set; }

    public int? Reviews { get; set; }

    public string CreateBy { get; set; }

    public int? Rank { get; set; }

    public double? Rating { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    public virtual ICollection<CourseSubCategory> CourseSubCategories { get; set; } = new List<CourseSubCategory>();

    public virtual ICollection<EnrollCourse> EnrollCourses { get; set; } = new List<EnrollCourse>();
}