// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Deposit
{
    public string Id { get; set; }

    public string WalletId { get; set; }

    public double? Total { get; set; }
    public string Stk { get; set; }           
    public string BankName { get; set; }       
    public string AccountName { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CancelReason { get; set; }

    public int? Status { get; set; }

    public virtual Wallet Wallet { get; set; }
}