// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class EnrollCourse
{
    public string Id { get; set; }

    public string CourseId { get; set; }

    public string MemberId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? Rating { get; set; }

    public double? Price { get; set; }

    public double? Processing { get; set; }

    public string Feedback { get; set; }

    public bool? IsOpen { get; set; }

    public int? Status { get; set; }

    public virtual Course Course { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<Processing> Processings { get; set; } = new List<Processing>();
}