// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Lecture
{
    public string Id { get; set; }

    public int? ChapNum { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public TimeOnly? TimeVideo { get; set; }

    public string VideoUrl { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Type { get; set; }

    public string LectureMetadata { get; set; }

    public int? Status { get; set; }
}