// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class MemberMemberShip
{
    public string Id { get; set; }

    public string MemberId { get; set; }

    public string MemberShipId { get; set; }

    public double? Price { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public int? Status { get; set; }

    public virtual Member Member { get; set; }

    public virtual MemberShip MemberShip { get; set; }
}