// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class MemberShip
{
    public string Id { get; set; }

    public string MemberShipName { get; set; }

    public int? Rank { get; set; }

    public int? DiscountCourse { get; set; }

    public int? DiscountBooking { get; set; }

    public double? Price { get; set; }

    public int? ExpiryDate { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<MemberMemberShip> MemberMemberShips { get; set; } = new List<MemberMemberShip>();
}