// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Member
{
    public string Id { get; set; }

    public string AccountId { get; set; }

    public string Fullname { get; set; }
    public string Avatar { get; set; }
    public string Phone { get; set; }

    public DateTime? Dob { get; set; }

    public string Mbti { get; set; }

    public string Disc { get; set; }

    public string LoveLanguage { get; set; }

    public string BigFive { get; set; }

    public string Gender { get; set; }

    public string Rec1 { get; set; }

    public string Rec2 { get; set; }

    public int? Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Booking> BookingMember2s { get; set; } = new List<Booking>();

    public virtual ICollection<Booking> BookingMembers { get; set; } = new List<Booking>();

    public virtual ICollection<Couple> CoupleFemaleNavigations { get; set; } = new List<Couple>();

    public virtual ICollection<Couple> CoupleMaleNavigations { get; set; } = new List<Couple>();

    public virtual ICollection<EnrollCourse> EnrollCourses { get; set; } = new List<EnrollCourse>();

    public virtual ICollection<MemberMemberShip> MemberMemberShips { get; set; } = new List<MemberMemberShip>();

    public virtual ICollection<ResultHistory> ResultHistories { get; set; } = new List<ResultHistory>();
}