// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Notification
{
    public string Id { get; set; }

    public string NotiType { get; set; }

    public string Description { get; set; }

    public bool? IsRead { get; set; }
    public bool? IsOpen { get; set; }

    public string DocNo { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? Status { get; set; }
}

