// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class PersonType
{
    public string Id { get; set; }

    public string CategoryId { get; set; }

    public string SurveyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }
    public string Detail { get; set; }

    public string Image { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ResultPersonType> ResultPersonTypePersonType2s { get; set; } = new List<ResultPersonType>();

    public virtual ICollection<ResultPersonType> ResultPersonTypePersonTypes { get; set; } = new List<ResultPersonType>();

    public virtual Survey Survey { get; set; }
}