// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Post
{
    public string Id { get; set; }

    public string CreateBy { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string? Image { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }
}