// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Processing
{
    public string Id { get; set; }

    public string ChapterId { get; set; }

    public string EnrollCourseId { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? Status { get; set; }

    public virtual Chapter Chapter { get; set; }

    public virtual EnrollCourse EnrollCourse { get; set; }
}