// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Question
{
    public string Id { get; set; }

    public int? ChapNum { get; set; }

    public string QuizId { get; set; }

    public string SurveyId { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public int? Score { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual Quiz Quiz { get; set; }

    public virtual Survey Survey { get; set; }
}