// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Quiz
{
    public string Id { get; set; }

    public int? QuizNum { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? TotalScore { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}