// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class ResultPersonType
{
    public string Id { get; set; }

    public string SurveyId { get; set; }

    public string CategoryId { get; set; }

    public string PersonTypeId { get; set; }

    public string PersonType2Id { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    public int Compatibility { get; set; }

    public string Image { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? Status { get; set; }
    public string? Weaknesses { get; set; }
    public string? StrongPoints { get; set; }
    public virtual Category Category { get; set; }

    public virtual PersonType PersonType { get; set; }

    public virtual PersonType PersonType2 { get; set; }
}