// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class SubCategory
{
    public string Id { get; set; }

    public string CategoryId { get; set; }

    public string Name { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<BookingSubCategory> BookingSubCategories { get; set; } = new List<BookingSubCategory>();

    public virtual Category Category { get; set; }

    public virtual ICollection<CounselorSubCategory> CounselorSubCategories { get; set; } = new List<CounselorSubCategory>();

    public virtual ICollection<CourseSubCategory> CourseSubCategories { get; set; } = new List<CourseSubCategory>();
}