// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class SysTransaction
{
    public string Id { get; set; }

    public string TransactionType { get; set; }

    public string DocNo { get; set; }

    public string CreateBy { get; set; }

    public DateTime? CreateDate { get; set; }
}