// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class Wallet
{
    public string Id { get; set; }

    public double? Remaining { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<Deposit> Deposits { get; set; } = new List<Deposit>();
}