// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPC.DAO.Models;

public partial class WorkSchedule
{
    public string Id { get; set; }

    public string CounselorId { get; set; }

    public DateTime? WorkDate { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public virtual Counselor Counselor { get; set; }
}